# Generated by Django 2.0.6 on 2018-07-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180702_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='templates',
            field=models.ManyToManyField(blank=True, to='web.Template'),
        ),
    ]
