# Generated by Django 2.0.6 on 2018-07-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_host_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='templates',
        ),
    ]
