# Generated by Django 2.0.6 on 2018-08-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='业务系统')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='厂商')),
            ],
        ),
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('user', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='用户使用率')),
                ('nice', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='NICE')),
                ('system', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='系统使用率')),
                ('idle', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='空闲率')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('status', models.CharField(blank=True, max_length=6, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Filesystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('mount_point', models.CharField(blank=True, max_length=64, verbose_name='挂载点')),
                ('Total_size', models.PositiveIntegerField(verbose_name='总大小')),
                ('used_size', models.PositiveIntegerField(verbose_name='已用')),
                ('avail_size', models.PositiveIntegerField(verbose_name='剩余')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('status', models.CharField(blank=True, max_length=6, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='主机名')),
                ('instance_name', models.CharField(max_length=64, verbose_name='实例名')),
                ('ip_addr', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('port', models.PositiveSmallIntegerField(default=22, verbose_name='端口号')),
                ('db_port', models.PositiveSmallIntegerField(default=1521, null=True, verbose_name='DB端口号')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('db_username', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('db_password', models.CharField(blank=True, max_length=128, null=True)),
                ('database_type', models.SmallIntegerField(choices=[(0, 'oracle 10g'), (1, 'oracle 11g'), (2, 'oracle 12c'), (3, 'mysql')], default=0, verbose_name='数据库类型')),
                ('os_type', models.SmallIntegerField(choices=[(0, 'Linux'), (1, 'windows'), (2, 'AIX')], default=0, verbose_name='OS类型')),
                ('opatch_version', models.CharField(max_length=64, verbose_name='补丁')),
                ('enabled', models.BooleanField(default=True)),
                ('is_database', models.BooleanField(default=True)),
                ('appcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.AppCompany', verbose_name='厂商')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Business', verbose_name='业务系统名称')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='LoadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('runtime', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('users', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('load1', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Buffers(Kb)')),
                ('load5', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Buffers(Kb)')),
                ('load15', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Buffers(Kb)')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('status', models.CharField(blank=True, max_length=6, verbose_name='状态')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
        migrations.CreateModel(
            name='MemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('MemTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='总内存(Kb)')),
                ('MemFree', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='未分配内存(Kb)')),
                ('Buffers', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Buffers(Kb)')),
                ('Cached', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Cached(Kb)')),
                ('SwapTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='总Swap(Kb)')),
                ('SwapFree', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='空闲swap(Kb)')),
                ('SwapUsage_p', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='swap使用率')),
                ('SwapUsage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已用swap(Kb)')),
                ('MemUsage_p', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='内存使用率')),
                ('MemUsage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已分配内存(Kb)')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('status', models.CharField(blank=True, max_length=6, verbose_name='状态')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='服务名称')),
                ('interval', models.IntegerField(default=60, verbose_name='监控间隔')),
                ('plugin_name', models.CharField(default='n/a', max_length=64, verbose_name='插件名')),
                ('has_sub_service', models.BooleanField(default=False, help_text='如果一个服务还有独立的子服务 ,选择这个,比如 网卡服务有多个独立的子网卡')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Tablespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('total_size', models.CharField(blank=True, max_length=64)),
                ('free_size', models.CharField(blank=True, max_length=64)),
                ('used_size', models.CharField(blank=True, max_length=64)),
                ('time', models.TimeField(auto_now_add=True, verbose_name='时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模版名称')),
                ('services', models.ManyToManyField(to='web.Service', verbose_name='服务列表')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.IDC', verbose_name='机房'),
        ),
        migrations.AddField(
            model_name='host',
            name='templates',
            field=models.ManyToManyField(blank=True, to='web.Template'),
        ),
        migrations.AddField(
            model_name='filesystem',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host'),
        ),
    ]
