# Generated by Django 2.0.6 on 2018-08-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='opatch_version',
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.SmallIntegerField(choices=[(0, 'Linux'), (1, 'windows'), (2, 'AIX'), (3, 'other')], default=0, verbose_name='OS类型'),
        ),
    ]
