# Generated by Django 2.0.6 on 2018-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180809_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
