# Generated by Django 2.0.6 on 2018-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_host_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_conn_type',
            field=models.SmallIntegerField(choices=[(0, 'ssh'), (1, 'telnet'), (2, 'snmp')], default=0, verbose_name='主机连接方式'),
        ),
    ]
