# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('instance_name', models.CharField(max_length=64)),
                ('ip_addr', models.GenericIPAddressField(unique=True)),
                ('port', models.PositiveSmallIntegerField(default=22)),
                ('username', models.CharField(max_length=64)),
                ('db_username', models.CharField(max_length=64)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('db_password', models.CharField(blank=True, max_length=128, null=True)),
                ('database_type', models.SmallIntegerField(choices=[(0, 'oracle 10g'), (1, 'oracle 11g'), (2, 'oracle 12c'), (3, 'mysql')], default=0)),
                ('os_type', models.SmallIntegerField(choices=[(0, 'Linux'), (1, 'windows'), (2, 'AIX')], default=0)),
                ('opatch_version', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('appcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.AppCompany')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Business')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.IDC'),
        ),
    ]
