# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-12 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='database_type',
            field=models.SmallIntegerField(choices=[(0, 'oracle 10g'), (1, 'oracle 11g'), (2, 'oracle 12c'), (3, 'mysql')], default=0, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='instance_name',
            field=models.CharField(max_length=64, verbose_name='实例名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip_addr',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='opatch_version',
            field=models.CharField(max_length=64, verbose_name='补丁'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_type',
            field=models.SmallIntegerField(choices=[(0, 'Linux'), (1, 'windows'), (2, 'AIX')], default=0, verbose_name='OS类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='username',
            field=models.CharField(max_length=64, verbose_name='用户名'),
        ),
    ]
