# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180612_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcompany',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='业务系统'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='机房'),
        ),
    ]
