# Generated by Django 2.0.6 on 2018-06-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180622_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablespace',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
