# Generated by Django 2.0.6 on 2018-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_host_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='templates',
            field=models.ManyToManyField(blank=True, to='web.Template'),
        ),
    ]
