# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180614_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablespace',
            name='free_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tablespace',
            name='total_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tablespace',
            name='used_size',
            field=models.FloatField(),
        ),
    ]
