# Generated by Django 2.0.6 on 2018-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180614_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablespace',
            name='free_size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tablespace',
            name='total_size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tablespace',
            name='used_size',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
