# Generated by Django 2.0.6 on 2018-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_cpuinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuinfo',
            name='idle',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='空闲率'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='nice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='NICE'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='system',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='系统使用率'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间'),
        ),
        migrations.AlterField(
            model_name='cpuinfo',
            name='user',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='用户使用率'),
        ),
    ]
