# Generated by Django 2.0.6 on 2018-07-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180704_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuinfo',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host'),
        ),
    ]
