# Generated by Django 2.0.6 on 2018-07-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_cpuinfo_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('MemTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='总内存(Kb)')),
                ('MemFree', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='空闲内存(Kb)')),
                ('Buffers', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Buffers(Kb)')),
                ('Cached', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Cached(Kb)')),
                ('SwapTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='总Swap(Kb)')),
                ('SwapFree', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='空闲swap(Kb)')),
                ('SwapUsage_p', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='swap使用率')),
                ('SwapUsage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已用swap(Kb)')),
                ('MemUsage_p', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='内存使用率')),
                ('MemUsage', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已用内存(Kb)')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
    ]
