# Generated by Django 2.0.6 on 2018-07-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_meminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filesystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('mount_point', models.CharField(blank=True, max_length=64, verbose_name='挂载点')),
                ('Total_size', models.PositiveIntegerField(verbose_name='总大小')),
                ('used_size', models.PositiveIntegerField(verbose_name='已用')),
                ('avail_size', models.PositiveIntegerField(verbose_name='剩余')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('status', models.CharField(blank=True, max_length=6, verbose_name='状态')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='status',
            field=models.CharField(blank=True, max_length=6, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='meminfo',
            name='status',
            field=models.CharField(blank=True, max_length=6, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='meminfo',
            name='MemFree',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='未分配内存(Kb)'),
        ),
        migrations.AlterField(
            model_name='meminfo',
            name='MemUsage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已分配内存(Kb)'),
        ),
    ]
