# Generated by Django 2.0.6 on 2018-07-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180704_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('runtime', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('users', models.CharField(blank=True, max_length=64, verbose_name='IP地址')),
                ('load1', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Buffers(Kb)')),
                ('load5', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Buffers(Kb)')),
                ('load15', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Buffers(Kb)')),
                ('time', models.CharField(blank=True, max_length=64, null=True, verbose_name='采集时间')),
                ('status', models.CharField(blank=True, max_length=6, verbose_name='状态')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
    ]
