# Generated by Django 2.0.6 on 2018-07-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_host_db_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablespace',
            name='date',
        ),
    ]
