# Generated by Django 2.0.6 on 2018-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_tablespace_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='is_database',
            field=models.BooleanField(default=True),
        ),
    ]
