# Generated by Django 2.0.6 on 2018-07-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_host_is_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='items',
        ),
        migrations.DeleteModel(
            name='ServiceIndex',
        ),
    ]
