# Generated by Django 2.0.6 on 2018-07-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_loadinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='db_port',
            field=models.PositiveSmallIntegerField(default=1521, null=True, verbose_name='DB端口号'),
        ),
    ]
